//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JudgeCommentDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class JudgeComment
    {
        public string CaseNO { get; set; }
        public string WarrantNo { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public Nullable<System.DateTime> IssueTime { get; set; }
        public string BondHearing { get; set; }
        public string Behavior { get; set; }
        public string RightAdvised { get; set; }
        public string AdviseManner { get; set; }
        public string BondText { get; set; }
        public string BondDollar { get; set; }
        public string MiddleName { get; set; }
        public string AccusedNo { get; set; }
        public string AccusedName { get; set; }
        public string OffenseNo { get; set; }
        public string OffenseName { get; set; }
        public string OtherComments { get; set; }
        public string Status { get; set; }
        public int ID { get; set; }
        public string ProbableCause { get; set; }
        public Nullable<int> Review { get; set; }
        public string DenyReason { get; set; }
        public string Location { get; set; }
        public string BondDollarOther { get; set; }
        public string BondDesc { get; set; }
        public Nullable<bool> QueuePrinting { get; set; }
    }
}
